package book;

public interface MockParsingData {

  public static final String FAIL_RESULT_DOCUMENT =
      "<div class=\"ss_center Search3NoResult\" style=\"\">\n"
          + "\t\t\n"
          + "\t\t<div class=\"ss_line\">\n"
          + "            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + "            <tbody><tr>\n"
          + "           \t<td height=\"19\" style=\"padding:3px 0;\">\n"
          + "            <div class=\"search_t_g\"><span class=\"result_l\"></span>(으)로 <span class=\"result_l_gray\">통합검색</span>(을)를 검색한 결과 총 0 건의 상품이 검색되었습니다.</div></td>\n"
          + "            </tr>\n"
          + "        \t</tbody></table>\n"
          + "      \t</div>\n"
          + "        \n"
          + "        \n"
          + "        \n"
          + "        <div class=\"result_l_gray ss_space_w \">찾으시는  통합검색이(가) 없습니까? </div>\n"
          + "        <div class=\"ss_space_h10\"></div>\n"
          + "        <div class=\"ss_list_tit ss_space_w\">핵심 단어를 띄어쓰기하여 입력해주세요</div>\n"
          + "        <div class=\"ss_list_wbox\">\n"
          + "        \t<ul>\n"
          + "            \t<li>(예시) <span class=\"ss_t_pink\">미움</span>받을<span class=\"ss_t_pink\">용기</span> <b>→</b> <span class=\"ss_t_pink\">미움 용기</span></li>\n"
          + "                <li>(예시) <span class=\"ss_t_pink\">꽃</span>을보듯<span class=\"ss_t_pink\">너</span>를본다 <b>→</b> <span class=\"ss_t_pink\">꽃 너</span></li>\n"
          + "            </ul>\n"
          + "        </div>\n"
          + "\n"
          + "        \n"
          + "        \n"
          + "    </div>";

  public static final String SUCCESS_RESULT_DOCUMENT =
      "<div id=\"Search3_Result\" style=\"padding: 10px 0px 0px 0px;\">"
          + "<div class=\"ss_book_box\" itemid=\"169299418\">\n"
          + " <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + " <tbody><tr>\n"
          + " <td width=\"25\" align=\"left\" valign=\"top\" style=\"padding-right:5px;\">\n"
          + " <table width=\"18\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + " <tbody><tr><td><div style=\"text-align: center;\">2.</div></td></tr> <tr><td><div style=\"text-align: center;\"><input name=\"chkCart.K392534378\" type=\"checkbox\"></div></td></tr> </tbody></table>\n"
          + "\n"
          + " </td>\n"
          + " <td width=\"170\" align=\"left\" valign=\"top\">\n"
          + " <table width=\"150\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
          + " <tbody><tr><td style=\"\"><div style=\"position:relative;\"><a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=169299418\"><img src=\"https://image.aladin.co.kr/product/16929/94/cover150/k392534378_1.jpg\" width=\"150\" border=\"0\" class=\"i_cover\"></a></div></td></tr>\n"
          + "<tr><td style=\"text-align: left;\"><a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=169299418\" target=\"_blank\"><img src=\"//image.aladin.co.kr/img/search/icon_new2.gif\" border=\"0\"></a><a href=\"/shop/book/wletslookViewer.aspx?ISBN=K392534378\" target=\"_blank\"><img src=\"//image.aladin.co.kr/img/search/icon_pv2.gif\" border=\"0\"></a></td></tr> </tbody></table>\n"
          + "\n"
          + " </td>\n"
          + " <td width=\"*\" align=\"left\" valign=\"top\">\n"
          + "     <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + "     <tbody><tr>\n"
          + "     <td width=\"*\" valign=\"top\">\n"
          + " <div class=\"ss_book_list\"><ul>\n"
          + "<li><span class=\"ss_ht1\">[<a href=\"/events/wevent_redirect.aspx?eventid=204611\">수험서.외국어.컴퓨터.대학교재 4만원 이상, 라떼 유리컵/스톱워치/본투리드 볼펜</a>]</span><br></li><li><span style=\"font-size: 14px;\">[국내도서]</span>&nbsp;<a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=169299418\" class=\"bo3\"><b>리팩토링 자바스크립트 Refactoring JavaScript</b></a><span class=\"ss_f_g2\"> - 테스트와 리팩토링 개념부터 계층 구조, OOP 패턴, 비동기, 함수형 프로그래밍 리팩토링까지</span>&nbsp;</li>\n"
          + " <li><a href=\"/Search/wSearchResult.aspx?AuthorSearch=에반+버차드@2515353&amp;BranchType=1\">에반 버차드</a> (지은이), <a href=\"/Search/wSearchResult.aspx?AuthorSearch=김건희@6420285&amp;BranchType=1\">김건희</a> (옮긴이) | <a href=\"/search/wsearchresult.aspx?PublisherSearch=%b1%e6%b9%fe@663&amp;BranchType=1\">길벗</a> | 2018년 10월</li><li><span class=\"\">36,000</span>원 → <span class=\"ss_p2\"><b><span class=\"\">32,400</span>원</b></span> (<span class=\"ss_p\">10%</span>할인),  마일리지 <span class=\"ss_p\">1,800</span>원 (<span class=\"ss_p\">5%</span> 적립)</li><li><img src=\"//image.aladin.co.kr/img/common/star_s4.gif\" border=\"0\" style=\"vertical-align: middle;\"> (<a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=169299418#K392534378_CommentReview\">2</a>) | 세일즈포인트 :<b> 636</b></li> </ul></div>\n"
          + "\n"
          + "<div class=\"ss_book_list\"><ul>\n"
          + "<li>지금 <strong>택배</strong>로 주문하면 <strong>내일</strong> 수령<div>최근 1주 92.3% (중구 중림동) <img src=\"//image.aladin.co.kr/img/shop/2012/bu_driveaway_ch.gif\" onclick=\"FindZipByList('addInputShop_169299418');\" style=\"cursor:pointer;vertical-align:middle;margin:-3px 0 0 0px;\" alt=\"지역변경\"><span id=\"addInputShop_169299418\"></span></div></li></ul></div>\n"
          + "\n"
          + "     </td>\n"
          + "     <td width=\"80\" valign=\"top\">\n"
          + "<div class=\"book_Rfloat_02\"><div class=\"button_search_cart_new\"><a href=\"/shop/wbasket.aspx?AddBook=K392534378\" onclick=\"return SafeBasket_ListOneAddByAjax('K392534378', document.getElementById('divBasketAddResult_K392534378'), {top: 0, left: -55});\">장바구니</a></div><div id=\"divBasketAddResult_K392534378\"></div><div class=\"button_search_buyitnow_new\"><a href=\"https://www.aladin.co.kr/order/worder_chk_order.aspx?CartType=4&amp;ISBN=K392534378\" onclick=\"return QuickBuyCheck('K392534378');\">바로구매</a></div><div class=\"Search3_Result_SafeBasketArea\" isbn=\"K392534378\" style=\"position: relative;\"><div class=\"button_search_storage\"><a href=\"javascript:void(0);\">보관함 <img alt=\"\" src=\"//image.aladin.co.kr/img/search/btn_bg5_arrow.png\"></a></div> <ul class=\"mylist Search3_Result_SafeBasketLayer\" isbn=\"K392534378\" style=\"display: none;\"><li><a href=\"javascript:void(0);\" onclick=\"return AddSafeBasket('K392534378');\">보관함</a></li><li><a href=\"javascript:void(0);\" onclick=\"return AddMyList('K392534378');\">마이리스트</a></li> </ul>\n"
          + "</div></div>\n"
          + "     </td>\n"
          + "     </tr>\n"
          + "     <tr>\n"
          + "     <td colspan=\"2\">\n"
          + "\n"
          + "\n"
          + "     </td>\n"
          + "     </tr>\n"
          + "     </tbody></table>\n"
          + " </td>\n"
          + " </tr>\n"
          + " </tbody></table>\n"
          + " </div>"
          + "<div class=\"ss_book_box\" itemid=\"169299418\">\n"
          + " <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + " <tbody><tr>\n"
          + " <td width=\"25\" align=\"left\" valign=\"top\" style=\"padding-right:5px;\">\n"
          + " <table width=\"18\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + " <tbody><tr><td><div style=\"text-align: center;\">2.</div></td></tr> <tr><td><div style=\"text-align: center;\"><input name=\"chkCart.K392534378\" type=\"checkbox\"></div></td></tr> </tbody></table>\n"
          + "\n"
          + " </td>\n"
          + " <td width=\"170\" align=\"left\" valign=\"top\">\n"
          + " <table width=\"150\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
          + " <tbody><tr><td style=\"\"><div style=\"position:relative;\"><a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=169299418\"><img src=\"https://image.aladin.co.kr/product/16929/94/cover150/k392534378_1.jpg\" width=\"150\" border=\"0\" class=\"i_cover\"></a></div></td></tr>\n"
          + "<tr><td style=\"text-align: left;\"><a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=169299418\" target=\"_blank\"><img src=\"//image.aladin.co.kr/img/search/icon_new2.gif\" border=\"0\"></a><a href=\"/shop/book/wletslookViewer.aspx?ISBN=K392534378\" target=\"_blank\"><img src=\"//image.aladin.co.kr/img/search/icon_pv2.gif\" border=\"0\"></a></td></tr> </tbody></table>\n"
          + "\n"
          + " </td>\n"
          + " <td width=\"*\" align=\"left\" valign=\"top\">\n"
          + "     <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + "     <tbody><tr>\n"
          + "     <td width=\"*\" valign=\"top\">\n"
          + " <div class=\"ss_book_list\"><ul>\n"
          + "<li><span class=\"ss_ht1\">[<a href=\"/events/wevent_redirect.aspx?eventid=204611\">수험서.외국어.컴퓨터.대학교재 4만원 이상, 라떼 유리컵/스톱워치/본투리드 볼펜</a>]</span><br></li><li><span style=\"font-size: 14px;\">[국내도서]</span>&nbsp;<a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=169299418\" class=\"bo3\"><b>리팩토링 자바스크립트 Refactoring JavaScript</b></a><span class=\"ss_f_g2\"> - 테스트와 리팩토링 개념부터 계층 구조, OOP 패턴, 비동기, 함수형 프로그래밍 리팩토링까지</span>&nbsp;</li>\n"
          + " <li><a href=\"/Search/wSearchResult.aspx?AuthorSearch=에반+버차드@2515353&amp;BranchType=1\">에반 버차드</a> (지은이), <a href=\"/Search/wSearchResult.aspx?AuthorSearch=김건희@6420285&amp;BranchType=1\">김건희</a> (옮긴이) | <a href=\"/search/wsearchresult.aspx?PublisherSearch=%b1%e6%b9%fe@663&amp;BranchType=1\">길벗</a> | 2018년 10월</li><li><span class=\"\">36,000</span>원 → <span class=\"ss_p2\"><b><span class=\"\">32,400</span>원</b></span> (<span class=\"ss_p\">10%</span>할인),  마일리지 <span class=\"ss_p\">1,800</span>원 (<span class=\"ss_p\">5%</span> 적립)</li><li><img src=\"//image.aladin.co.kr/img/common/star_s4.gif\" border=\"0\" style=\"vertical-align: middle;\"> (<a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=169299418#K392534378_CommentReview\">2</a>) | 세일즈포인트 :<b> 636</b></li> </ul></div>\n"
          + "\n"
          + "<div class=\"ss_book_list\"><ul>\n"
          + "<li>지금 <strong>택배</strong>로 주문하면 <strong>내일</strong> 수령<div>최근 1주 92.3% (중구 중림동) <img src=\"//image.aladin.co.kr/img/shop/2012/bu_driveaway_ch.gif\" onclick=\"FindZipByList('addInputShop_169299418');\" style=\"cursor:pointer;vertical-align:middle;margin:-3px 0 0 0px;\" alt=\"지역변경\"><span id=\"addInputShop_169299418\"></span></div></li></ul></div>\n"
          + "\n"
          + "     </td>\n"
          + "     <td width=\"80\" valign=\"top\">\n"
          + "<div class=\"book_Rfloat_02\"><div class=\"button_search_cart_new\"><a href=\"/shop/wbasket.aspx?AddBook=K392534378\" onclick=\"return SafeBasket_ListOneAddByAjax('K392534378', document.getElementById('divBasketAddResult_K392534378'), {top: 0, left: -55});\">장바구니</a></div><div id=\"divBasketAddResult_K392534378\"></div><div class=\"button_search_buyitnow_new\"><a href=\"https://www.aladin.co.kr/order/worder_chk_order.aspx?CartType=4&amp;ISBN=K392534378\" onclick=\"return QuickBuyCheck('K392534378');\">바로구매</a></div><div class=\"Search3_Result_SafeBasketArea\" isbn=\"K392534378\" style=\"position: relative;\"><div class=\"button_search_storage\"><a href=\"javascript:void(0);\">보관함 <img alt=\"\" src=\"//image.aladin.co.kr/img/search/btn_bg5_arrow.png\"></a></div> <ul class=\"mylist Search3_Result_SafeBasketLayer\" isbn=\"K392534378\" style=\"display: none;\"><li><a href=\"javascript:void(0);\" onclick=\"return AddSafeBasket('K392534378');\">보관함</a></li><li><a href=\"javascript:void(0);\" onclick=\"return AddMyList('K392534378');\">마이리스트</a></li> </ul>\n"
          + "</div></div>\n"
          + "     </td>\n"
          + "     </tr>\n"
          + "     <tr>\n"
          + "     <td colspan=\"2\">\n"
          + "\n"
          + "\n"
          + "     </td>\n"
          + "     </tr>\n"
          + "     </tbody></table>\n"
          + " </td>\n"
          + " </tr>\n"
          + " </tbody></table>\n"
          + " </div>"
          + "<div class=\"ss_book_box\" itemid=\"111691505\">\n"
          + " <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + " <tbody><tr>\n"
          + " <td width=\"25\" align=\"left\" valign=\"top\" style=\"padding-right:5px;\">\n"
          + " <table width=\"18\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + " <tbody><tr><td><div style=\"text-align: center;\">3.</div></td></tr> <tr><td><div style=\"text-align: center;\"><input name=\"chkCart.0134757599\" type=\"checkbox\"></div></td></tr> </tbody></table>\n"
          + "\n"
          + " </td>\n"
          + " <td width=\"170\" align=\"left\" valign=\"top\">\n"
          + " <table width=\"150\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
          + " <tbody><tr><td style=\"\"><div style=\"position:relative;\"><a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=111691505\"><img src=\"https://image.aladin.co.kr/product/11169/15/cover150/0134757599_2.jpg\" width=\"150\" border=\"0\" class=\"i_cover\"></a></div></td></tr>\n"
          + "<tr><td style=\"text-align: left;\"><a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=111691505\" target=\"_blank\"><img src=\"//image.aladin.co.kr/img/search/icon_new2.gif\" border=\"0\"></a><a href=\"/shop/book/wletslookViewer.aspx?ISBN=0134757599\" target=\"_blank\"><img src=\"//image.aladin.co.kr/img/search/icon_pre.gif\" border=\"0\"></a></td></tr> </tbody></table>\n"
          + "\n"
          + " </td>\n"
          + " <td width=\"*\" align=\"left\" valign=\"top\">\n"
          + "     <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + "     <tbody><tr>\n"
          + "     <td width=\"*\" valign=\"top\">\n"
          + " <div class=\"ss_book_list\"><ul>\n"
          + "<li><span style=\"font-size: 14px;\">[외국도서]</span>&nbsp;<a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=111691505\" class=\"bo3\"><b>Refactoring: Improving the Design of Existing Code (Hardcover, 2)</b></a>&nbsp;&nbsp;<img src=\"//image.aladin.co.kr/img/shop/2012/bu_free.gif\" border=\"0\" align=\"absmiddle\"></li>\n"
          + " <li><a href=\"/Search/wSearchResult.aspx?AuthorSearch=마틴+파울러@64557&amp;BranchType=7\">마틴 파울러</a> (지은이) | <a href=\"/search/wsearchresult.aspx?PublisherSearch=Addison-Wesley+Professional@22524&amp;BranchType=7\">Addison-Wesley Professional</a> | 2018년 11월</li><li><span class=\"\">79,000</span>원 → <span class=\"ss_p2\"><b><span class=\"\">79,000</span>원</b></span>,  마일리지 <span class=\"ss_p\">1,580</span>원 (<span class=\"ss_p\">2%</span> 적립)</li><li><img src=\"//image.aladin.co.kr/img/common/star_s10.gif\" border=\"0\" style=\"vertical-align: middle;\"> (<a href=\"https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=111691505#0134757599_CommentReview\">1</a>) | 세일즈포인트 :<b> 163</b></li> </ul></div>\n"
          + "\n"
          + "<div class=\"ss_book_list\"><ul>\n"
          + "<li>지금 <strong>택배</strong>로 주문하면 <strong>5월 6일 출고</strong><div>최근 1주 92.3% (중구 중림동) <img src=\"//image.aladin.co.kr/img/shop/2012/bu_driveaway_ch.gif\" onclick=\"FindZipByList('addInputShop_111691505');\" style=\"cursor:pointer;vertical-align:middle;margin:-3px 0 0 0px;\" alt=\"지역변경\"><span id=\"addInputShop_111691505\"></span></div></li></ul></div>\n"
          + "\n"
          + "     </td>\n"
          + "     <td width=\"80\" valign=\"top\">\n"
          + "<div class=\"book_Rfloat_02\"><div class=\"button_search_cart_new\"><a href=\"/shop/wbasket.aspx?AddBook=0134757599\" onclick=\"return SafeBasket_ListOneAddByAjax('0134757599', document.getElementById('divBasketAddResult_0134757599'), {top: 0, left: -55});\">장바구니</a></div><div id=\"divBasketAddResult_0134757599\"></div><div class=\"button_search_buyitnow_new\"><a href=\"https://www.aladin.co.kr/order/worder_chk_order.aspx?CartType=4&amp;ISBN=0134757599\" onclick=\"return QuickBuyCheck('0134757599');\">바로구매</a></div><div class=\"Search3_Result_SafeBasketArea\" isbn=\"0134757599\" style=\"position: relative;\"><div class=\"button_search_storage\"><a href=\"javascript:void(0);\">보관함 <img alt=\"\" src=\"//image.aladin.co.kr/img/search/btn_bg5_arrow.png\"></a></div> <ul class=\"mylist Search3_Result_SafeBasketLayer\" isbn=\"0134757599\" style=\"display: none;\"><li><a href=\"javascript:void(0);\" onclick=\"return AddSafeBasket('0134757599');\">보관함</a></li><li><a href=\"javascript:void(0);\" onclick=\"return AddMyList('0134757599');\">마이리스트</a></li> </ul>\n"
          + "</div></div>\n"
          + "     </td>\n"
          + "     </tr>\n"
          + "     <tr>\n"
          + "     <td colspan=\"2\">\n"
          + "<table width=\"440px\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-bottom:15px;\"><tbody><tr><td valign=\"top\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tbody><tr><td width=\"33%\" valign=\"top\">\n"
          + "                <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + "\t\t        <tbody><tr><td height=\"1\" bgcolor=\"#d9d9d9\"></td></tr>\n"
          + "\t\t        <tr><td height=\"40\" align=\"center\" bgcolor=\"#f9f9f9\" style=\"text-align: center !important;\"><span class=\"bo_used\">알라딘 중고</span></td></tr>\n"
          + "\t\t        <tr><td height=\"1\" align=\"center\" bgcolor=\"#ececec\"></td></tr>\n"
          + "\t\t        <tr><td height=\"30\" align=\"center\" style=\"text-align: center !important;\"><span class=\"bo_used\">-</span></td></tr>\n"
          + "\t\t        <tr><td height=\"1\" align=\"center\" bgcolor=\"#ececec\"></td></tr>\n"
          + "\t\t        </tbody></table></td><td width=\"33%\" valign=\"top\">\n"
          + "                <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + "\t\t        <tbody><tr><td height=\"1\" bgcolor=\"#d9d9d9\"></td></tr>\n"
          + "\t\t        <tr><td height=\"40\" align=\"center\" bgcolor=\"#f9f9f9\" style=\"text-align: center !important;\"><span class=\"bo_used\">이 광활한 우주점</span></td></tr>\n"
          + "\t\t        <tr><td height=\"1\" align=\"center\" bgcolor=\"#ececec\"></td></tr>\n"
          + "\t\t        <tr><td height=\"30\" align=\"center\" style=\"text-align: center !important;\"><span class=\"bo_used\">-</span></td></tr>\n"
          + "\t\t        <tr><td height=\"1\" align=\"center\" bgcolor=\"#ececec\"></td></tr>\n"
          + "\t\t        </tbody></table></td><td width=\"33%\" valign=\"top\">\n"
          + "                <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n"
          + "\t\t        <tbody><tr><td height=\"1\" bgcolor=\"#d9d9d9\"></td></tr>\n"
          + "\t\t        <tr><td height=\"40\" align=\"center\" bgcolor=\"#f9f9f9\" style=\"text-align: center !important;\"><span class=\"bo_used\">판매자 중고</span></td></tr>\n"
          + "\t\t        <tr><td height=\"1\" align=\"center\" bgcolor=\"#ececec\"></td></tr>\n"
          + "\t\t        <tr><td height=\"30\" align=\"center\" style=\"text-align: center !important;\"><span class=\"bo_used\">-</span></td></tr>\n"
          + "\t\t        <tr><td height=\"1\" align=\"center\" bgcolor=\"#ececec\"></td></tr>\n"
          + "\t\t        </tbody></table></td></tr></tbody></table></td></tr></tbody></table>\n"
          + "\n"
          + "     </td>\n"
          + "     </tr>\n"
          + "     </tbody></table>\n"
          + " </td>\n"
          + " </tr>\n"
          + " </tbody></table>\n"
          + " </div>"
          + "</div>";
}
